package-lock.json
package.json

`@snyk/code-client` has changed the code logic around file ignoring. This has fixed the issue, where .dcignore and .gitignore were not taken into account when performing analysis.

fix: ignore .gitignore and .dcignore files [ROAD-33]

---

src/extension.ts
src/interfaces/SnykInterfaces.ts
src/snyk/extension.ts
src/snyk/lib/modules/LoginModule.ts
src/snyk/lib/modules/SnykLib.ts
src/snyk/lib/modules/code.ts
src/snyk/services/cliConfigService.ts
src/snyk/services/notificationService.ts
src/snyk/services/userService.ts
src/snyk/view/SupportProvider.ts

- Introduce link to the feedback call to the tree view
- Notification refactoring is due to the initial assumption that we were planning to have bi-weekly notification to ask for feedback. The refactored code was kept for code responsibility separation reason.

feat: add feedback form link to the tree view [ROAD-93]

---

package.json
src/snyk/analytics/itly.ts
src/snyk/configuration.ts
src/snyk/lib/modules/ReportModule.ts
src/test/suite/extension.test.ts

Remove authHost and Url configuration settings not to confuse our users.

refactor: remove url and authHost setting [ROAD-123]

---

.itlyrc
src/itly/index.ts
src/snyk/analytics/itly.ts
src/snyk/extension.ts
src/snyk/lib/modules/SnykLib.ts
src/uninstall.ts

- Track 'Welcome View Is Viewed' event on view toggle instead of extension activation as it is now.
- Flush event on extension deactivation and uninstall
- Point Iteratively to the main branch

fix: track 'Welcome View Is Viewed' event on view toggle [ROAD-120]

---

src/interfaces/SnykInterfaces.ts
src/snyk/lib/modules/BaseSnykModule.ts
src/snyk/lib/modules/BundlesModule.ts
src/snyk/lib/modules/LoginModule.ts
src/snyk/lib/modules/SnykLib.ts
src/snyk/lib/watchers/SnykSettingsWatcher.ts

- Ensures extension is not restarted when "snyk.codeEnabled" setting is written
- Additional logging added

fix: prevent duplicate "Analysis is triggerred" event

---

.vscode/launch.json
src/extension.ts
src/snyk/configuration.ts
src/snyk/extension.ts
src/snyk/services/contextService.ts
src/snyk/services/viewManagerService.ts
src/snyk/view/welcome/welcomeViewProvider.ts
src/test/integration/runTest.ts
src/test/integration/viewNavigation.test.ts

- Adds a single test to check if Features webview is shown after authentication. Due to time constraints other tests were not added however the test suite is extensible. 
- Corrects webview class name for Features webview
- Configuration setting to return `undefined` instead of `null` to communicate setting absence and not a null pointer.

test: add view navigation integration test [ROAD-189]

---

README.md

Marketplace links lead to 404s so I've updated them to link to https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner

docs: fix marketplace links

---

CHANGELOG.md
package-lock.json
package.json

Since extension is published not bundled, modules are loaded from file system, thus prone to case sensitivity issues. Had to clean up the `out` directory locally that gets packaged, and release the patched version to Marketplace.

chore: release 1.2.1

---

media/views/snykCode/suggestion/suggestion.css
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewProvider.ts
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewScript.ts

In the Issue Details panel, underneath the Example fixes there are the commit comments.
We need to remove them because they do not reflect the example fixes and confuse the users.

[VSCode] Remove the commit comments [ROAD-409]

---

src/snyk/snykCode/codeActions/issuesActionsProvider.ts

This has been raised by @deepcodeg, where Snyk Code suggestion tab wouldn't be opening if triggered from quick fix.
v

fix: Snyk Code fix not opening up in editor

---

src/snyk/common/error/errorReporter.ts
src/snyk/common/user.ts

This could help to determine how many users are affected by the reported error. In some scenarios we can establish contact to help them.

feat: capture userId when reporting to Sentry [ROAD-471]

---

package.json
src/snyk/common/configuration/configuration.ts
src/snyk/common/constants/settings.ts
src/test/unit/common/configuration.test.ts

Feature flags will be part of settings configuration in VS Code extension. They will be stored under "snyk.features.preview" object-type setting, where keys are feature flags and values are bools indicating whether it's enabled or disabled. Absence of setting or a key of the object means it's disabled.
```
"snyk.features.preview": {
"reportFalsePositives": false,
"newGreatFeatureX": true
}
```
They are visible in UI but not easily accessible to prevent users from playing with them and bringing their extension into possible broken state. Here's the screenshot of settings UI:
Here's how it's surfaced within the corresponding JSON:

feat: add feature flags [ROAD-549]

---

README.md

Hello Snyk Team,
The Extension Configuration section currently has an out of date link to the current CLI Reference page: https://docs.snyk.io/features/snyk-cli/cli-reference. 
This PR updates the link to the correct url replacing this out of date url: https://docs.snyk.io/features/snyk-cli/guides-for-our-cli/cli-reference
Thanks,
Matt

Fix README.md Broken Link to CLI Reference

---

package.json

CSS files are not published in Preview version currently. This PR addresses this issue.
[Bug reported](https://snyk.slack.com/archives/C01FA88CUU9/p1645093151116409?thread_ts=1645021672.367459&cid=C01FA88CUU9)

fix: prepublish step with missing CSS files

---

package.json
src/snyk/base/modules/baseSnykModule.ts
src/snyk/base/modules/snykLib.ts
src/snyk/common/configuration/configuration.ts
src/snyk/common/constants/views.ts
src/snyk/common/services/cliConfigService.ts
src/snyk/common/vscode/uri.ts
src/snyk/extension.ts
src/snyk/snykCode/analyzer/analyzer.ts
src/snyk/snykCode/codeService.ts
src/snyk/snykCode/codeSettings.ts
src/test/unit/common/services/cliConfigService.test.ts
src/test/unit/snykCode/codeSettings.test.ts

I've started making `src/snyk/snykCode/analyzer/analyzer.ts` unit-testable but then realised it's not only analyzer that needs to invert dependencies but also quite some other classes `codeService.ts` depends on, thus extracted SAST enablement logic in a separate class instead. I've preserved changes to `analyzer.ts` since it's another small step forward to allow unit testing for `codeService.ts`.

feat: block LCE upload for Snyk Code [ROAD-712]

---

package.json
src/snyk/base/modules/baseSnykModule.ts
src/snyk/base/modules/interfaces.ts
src/snyk/base/services/authenticationService.ts
src/snyk/common/constants/views.ts
src/snyk/common/error/errorHandler.ts
src/snyk/common/messages/errors.ts
src/snyk/common/vscode/types.ts
src/snyk/snykCode/analyzer/analyzer.ts
src/snyk/snykCode/codeService.ts
src/snyk/snykCode/error/snykCodeErrorHandler.ts
src/snyk/snykCode/messages/analysis.ts
src/snyk/snykCode/views/issueTreeProvider.ts
src/test/unit/base/services/authenticationService.test.ts
src/test/unit/snykCode/error/snykCodeErrorHandler.test.ts

- I've wired existing retry strategy for transient errors.
- I've also replaced the general transient view with specific tree node in "Code Security & Quality" view. The old "general" view was there since Snyk acquired Deepcode and is not relevant any more, since Snyk Code is one of multiple product integrations nowadays.
- Fixed log message in the output channel to have enough verbosity and not report empty objects `{}`

fix: Failed to get remote bundle reports from Snyk Code [ROAD-683]

---

src/snyk/common/views/webviewPanelSerializer.ts
src/snyk/common/views/webviewProvider.ts
src/snyk/common/vscode/types.ts
src/snyk/snykCode/views/falsePositive/falsePositiveWebviewProvider.ts
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewProvider.ts
src/snyk/snykOss/views/suggestion/ossSuggestionWebviewProvider.ts

I've noticed that some people are still getting empty webview without JS and images loaded even after https://github.com/snyk/vscode-extension/pull/151. Did get this issue myself again.
It seems this could stem from [this issue](https://github.com/microsoft/vscode/issues/114659). I've applied the same fix as [in PR](https://github.com/microsoft/vscode-extension-samples/pull/376) for the sample webview code in `vscode-samples` repo. Hope this resolves the issue forever.
cc @deepcodeg

fix: potential webview state deserialization [ROAD-605]

---

src/snyk/common/messages/analysisMessages.ts
src/snyk/common/views/analysisTreeNodeProvider.ts

Removing the time stat from the analysis tree and just simply displaying the date and time the analysis finished at.
Changed from `Analysis took <duration>, finished at <time>,<date>` to `Analysis finished at <time>,<date>`.

fix: remove the duration from analysis tree [ROAD-312]

---

package-lock.json
package.json
src/snyk/base/modules/baseSnykModule.ts
src/snyk/cli/api/staticCliApi.ts
src/snyk/cli/process.ts
src/snyk/cli/services/cliService.ts
src/snyk/common/api/apiСlient.ts
src/snyk/common/proxy.ts
src/snyk/extension.ts
src/snyk/snykCode/codeService.ts
src/snyk/snykOss/api/npmTestApi.ts
src/snyk/snykOss/services/vulnerabilityCount/npmModuleInfoFetchService.ts
src/test/unit/cli/process.test.ts
src/test/unit/common/proxy.test.ts

This PR enables passing proxy configuration to all network requests for the following scenarios:
1. Environment is set up using proxy variables
2. Proxy is added manually in VS Code settings.
All calls that are issued from within the extension codebase, `code-client` dependency as well as Snyk CLI now respect the above setups.

fix: respect proxy environments [ROAD-722]

---

src/snyk/common/analytics/itly.ts
src/snyk/common/experiment/services/experimentService.ts
src/snyk/common/watchers/settingsWatcher.ts
src/snyk/extension.ts
src/test/unit/common/experiment/services/experimentService.test.ts
src/uninstall.ts

Currently if you do not have `snyk.config.local.json` configuration file populated with correct API keys in order to run extension in development mode the extension throws an error and does not successfully startup.
This PR fixes that by isolating the error reporting configuration piece and allowing the extension to startup successfully without needing to have all the reporting keys available.

fix: allow running extension without snyk.config.local.json values in development [ROAD-714]

---

src/snyk/base/modules/baseSnykModule.ts
src/snyk/base/modules/snykLib.ts
src/snyk/common/api/apiСlient.ts
src/snyk/common/error/errorHandler.ts
src/snyk/common/services/cliConfigService.ts
src/snyk/common/user.ts
src/snyk/snykCode/codeSettings.ts

When providing an invalid/revoked token the API responds with error code `401` which not being handled correctly navigates the user to error screen. This PR fixes that problem and navigates the user back to the welcome screen where user can generate a new token.

fix: navigating user back to the welcome screen in case of an invalid token [ROAD-642]

---

.github/workflows/release-stable.yaml

Introducing weekly automated stable release. That performs,
- Build the source code
- Bumps the patch version (based on the previous tag)
- Add required credentials 
- Create a release with the relevant files and release notes (notes should be same as changelog.md)
- Publish to marketplace

fix: Automated weekly release [ROAD-223]

---

.github/workflows/release-stable.yaml

Adding some indentation for on trigger because yaml 😫

chore: indent on trigger correctly in release-stable yaml for GH actions

---

src/snyk/cli/process.ts
src/test/unit/base/services/authenticationService.test.ts

Mocks for Needle client that we use within our tests has a default timeout set to 10 minutes (within code-client package) which hangs the socket for that time and tests takes 10 minutes to complete. 
- Adding an override for that timeout.
- Removing an unnessary logging statement.

fix: unit test mocks hanging up

---

CHANGELOG.md
src/snyk/common/views/analysisTreeNodeProvider.ts
src/snyk/common/watchers/configurationWatcher.ts
src/snyk/snykCode/analyzer/analyzer.ts
src/snyk/snykCode/codeService.ts
src/snyk/snykCode/interfaces.ts
src/snyk/snykCode/utils/analysisUtils.ts
src/snyk/snykCode/views/issueTreeProvider.ts
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewProvider.ts
src/test/unit/common/configuration.test.ts
src/test/unit/mocks/workspace.mock.ts
src/test/unit/snykCode/analyzer/analyzer.test.ts

- Remove diagnostics when Snyk Code is disabled
- Update diagnostics when filters are applied
- Refactor analyzer.ts to be unit-testable
As part of addressing this issue I've noticed that Open Source Security still reports diagnostics when OSS is disabled. I've added [another ticket](https://snyksec.atlassian.net/browse/ROAD-834) for this.

fix: Snyk Code diagnostics to respect settings [ROAD-638]

---

src/snyk/common/error/errorHandler.ts
src/snyk/common/error/errorReporter.ts
src/snyk/snykCode/codeService.ts
src/snyk/snykCode/error/snykCodeErrorHandler.ts
src/test/unit/base/services/authenticationService.test.ts
src/test/unit/common/error/errorReporter.test.ts
src/test/unit/snykCode/error/snykCodeErrorHandler.test.ts

- Adding `requestId` to error reporting. Follow pattern described here https://blog.sentry.io/2019/01/31/using-nginx-sentry-trace-errors-logs
- Moving analytics event reporting to once the retry mechanism is exhausted.
This should enable for us to correlate the events we see during error reporting and essentially thread it through the system.

feat: add request id to reporting

---

CHANGELOG.md
src/snyk/common/configuration/configuration.ts
src/test/unit/common/configuration.test.ts

This PR adds a support for single tenant setups.

feat: add support for single tenant setups [ROAD-829]

---

src/snyk/advisor/services/advisorService.ts
src/snyk/common/services/moduleParserProvider.ts
src/snyk/extension.ts
src/snyk/snykOss/services/vulnerabilityCount/ossVulnerabilityCountService.ts
src/snyk/snykOss/services/vulnerabilityCount/parsers/packageJsonParser.ts
src/test/unit/advisor/services/advisorService.test.ts
src/test/unit/snykOss/services/vulnerabilityCount/ossVulnerabilityCountService.test.ts
src/test/unit/snykOss/services/vulnerabilityCount/parsers/moduleParserProvider.test.ts
src/test/unit/snykOss/services/vulnerabilityCount/parsers/packageJsonParser.test.ts

Fixes #173.
<details>
<summary>Screenshot</summary>
</details>
As `--dev` is the trigger for scanning `devDependencies`, I've approached the issue like this:
1. Pass the additional CLI parameters to the package.json parser;
2. Look for the `--dev` string inside the parameters (if provided)
3. Check if there are `devDependencies` in the package.json
4. If 2 and 3 are true, parse the `devDependencies` as the `dependencies`
Let me know if you have suggestions for changes or if I have approached the issue incorrectly.

feat: support devDependencies on package.json parser

---

CHANGELOG.md
package.json
src/snyk/common/configuration/configuration.ts
src/snyk/common/services/learnService.ts

Signed-off-by: Aayush Attri <aayush.attri@snyk.io>
The token retrieval method within `SecretStorage` class throws an error when the token cannot be parsed which creates a generic error that we want to handle for.
Also removing a `console.log` within `src/snyk/common/services/learnService.ts`

fix: token retrieval error handling

---

CHANGELOG.md
src/snyk/snykCode/analyzer/analyzer.ts
src/snyk/snykCode/codeService.ts
src/snyk/snykCode/falsePositive/falsePositive.ts
src/snyk/snykCode/utils/analysisUtils.ts
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewProvider.ts
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewScript.ts
src/test/unit/mocks/languages.mock.ts
src/test/unit/mocks/uri.mock.ts
src/test/unit/mocks/workspace.mock.ts
src/test/unit/snykCode/falsePositive/falsePositive.test.ts
src/test/unit/snykCode/utils/analysisUtils.test.ts

Fixes Snyk Code inter-file issue display that don't link to the markers' reported files currently. The fix is applied to related diagnostics and fixes navigation from the Code suggestion webview.
I believe we should introduce Dependency Injection quite soon, since constructor injections become quite verbose now.

fix: inter-file code flow in diagnostics [ROAD-864]

---

.github/workflows/release-stable.yaml
src/snyk/common/configuration/configuration.ts
src/test/unit/common/configuration.test.ts

TIL: Thenable errors are not caught within a try/catch block so need to create a new promise out of Thenables to correctly handle with the errors.

fix: token error

---

.github/workflows/readme-sync.yaml

- Readme sync to clean up Gitbook hints in markdown.
- Readme sync to provide correct urls

fix: readme sync img urls and gitbook hints [ROAD-775]

---

.github/workflows/readme-sync.yaml

Always use HEAD for image urls in readme sync to prevent bot detecting changes when it's only remote git head hash update.

fix: always use HEAD for image urls in readme sync

---

.github/workflows/readme-sync.yaml

This fixes broken images when syncing readme from Gitbook.
Marketplace Markdown doesn't support special characters `<>` when adding a Markdown image. E.g. the following Markdown will not be printed correctly and instead interpreted as plaintext:
`![Visual Studio Code extension results](<https://github.com/snyk/user-docs/raw/HEAD/docs/.gitbook/assets/image (76) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1).png>)`.
The fix is to replace these with <img> HTML tag using `sed` as part of readme sync.

fix: broken images in readme sync

---

src/snyk/common/services/learnService.ts
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewProvider.ts
src/snyk/snykOss/views/suggestion/ossSuggestionWebviewProvider.ts
src/test/unit/common/services/learnService.test.ts

- Reason for PR: Learn wants to be able to provide lesson url's with query parameters already injected, existing code does not support this functionality
- Refactor no changes in functionality, made existing code more flexible to correctly parse a lesson URL query parameter
No visual change

chore: refactored the way we handle lean query params [OWL-1436]

---

.github/workflows/release-stable.yaml

VS Code release action fails when GitHub action is run as cron. It gets published to Marketplace, but the github release and tag aren’t created. Here’s an example: https://github.com/snyk/vscode-extension/runs/7519138993?check_suite_focus=true 
Reason: https://github.com/anothrNick/github-tag-action/issues/22

fix: git tag in release cron

---

CHANGELOG.md
package-lock.json
package.json
src/snyk/snykCode/analyzer/analyzer.ts
src/snyk/snykCode/codeService.ts
src/snyk/snykCode/error/snykCodeErrorHandler.ts

[We don't retry](https://snyk.slack.com/archives/C01DGQ3AT09/p1657719637337439?thread_ts=1657718577.507199&cid=C01DGQ3AT09) on 404 on extendBundle from code-client. This leads to plenty of Sentry errors due to this. This fix should address the problem.

fix: create new bundle on 404 when extending bundle [ZEN-262]

---

.github/workflows/release-stable.yaml

Fixes `Error: Parameter token or opts.auth is required` during version bump version.
https://github.com/snyk/vscode-extension/runs/7562384992?check_suite_focus=true

fix: pass args via params, not envs for release version bump

---

package-lock.json
package.json
src/snyk/base/modules/baseSnykModule.ts
src/snyk/common/vscode/hover.ts
src/snyk/common/vscode/window.ts
src/snyk/extension.ts
src/snyk/snykCode/analyzer/analyzer.ts
src/snyk/snykCode/codeService.ts
src/snyk/snykCode/hoverProvider/hoverProvider.ts
src/snyk/snykCode/interfaces.ts
src/test/unit/advisor/services/advisorService.test.ts
src/test/unit/snykCode/hoverProvider/hoverProvider.test.ts

We specify `vscode` engine as version `^1.58.0`, however types dependency `@types/vscode` is not consistent as it has `^1.48.0` version types. This PR updates this and fixes issues

fix: @types/vscode to match engine version

---

.github/workflows/release-stable.yaml

_Currently the `vsce package` command in the workflow will read the version from `package.json`. This is no longer manually maintained, so it will always be wrong. This PR computes the correct version suffix for `vsce package`._

fix: Build and Release workflow not putting version in .vsix file correctly

---

CHANGELOG.md
src/snyk/common/languageServer/languageServer.ts
src/snyk/common/languageServer/middleware.ts
src/snyk/common/languageServer/settings.ts
src/snyk/common/vscode/types.ts
src/test/unit/common/languageServer/languageServer.test.ts
src/test/unit/common/languageServer/middleware.test.ts

This PR adds a middleware that translates client responses to `workspace/configuration` request, mapping them to LS-expected values. Ideally, we shouldn't have it at all. A follow-up work will be created on how we can minimise/remove the translation.

feat: translate configuration keys to language server [ROAD-1086]

---

CHANGELOG.md
src/snyk/base/services/authenticationService.ts
src/snyk/common/constants/general.ts
src/snyk/common/constants/languageServer.ts
src/snyk/common/languageServer/languageServer.ts
src/snyk/common/vscode/languageClient.ts
src/snyk/common/vscode/types.ts
src/snyk/extension.ts
src/test/unit/base/services/authenticationService.test.ts

Signed-off-by: Bastian Doetsch <bastian.doetsch@snyk.io>
When a user manually enters a token with the setToken command, we need to inform Language Server of the new token. This PR implements sending a token via `DidChangeConfiguration` whenever the setToken command is yielding a valid token.

feat: send token to language server when updating token manually

---

src/snyk/common/languageServer/languageServer.ts
src/snyk/common/languageServer/middleware.ts
src/snyk/common/languageServer/settings.ts
src/snyk/extension.ts
src/test/unit/common/languageServer/languageServer.test.ts
src/test/unit/common/languageServer/middleware.test.ts

This aligns on settings that are passed in initialization request and upon LS querying them. This was originally [reported here](https://github.com/snyk/vscode-extension/pull/283#discussion_r955736288) by @bastiandoetsch

fix: settings synchronisation [ROAD-1086]

---

CHANGELOG.md
package-lock.json
package.json

On some machines @snyk/fast-glob causes performance bottleneck. Our @snyk/fast-glob fork is quite outdated and not maintained. `code-client` dropped this dependency and replaced with the official fast-glob lib in https://github.com/snyk/code-client/pull/160 as it provides some performance improvements.

fix: fast-glob performance issues [ROAD-1087]

---

src/snyk/common/languageServer/languageServer.ts
src/snyk/common/languageServer/middleware.ts
src/snyk/common/languageServer/settings.ts
src/snyk/extension.ts
src/test/unit/common/languageServer/languageServer.test.ts
src/test/unit/common/languageServer/middleware.test.ts

Ensures `anonymousId` synchronisation for analytics.

feat: pass anonymousId to language server [ROAD-1185]

---

CHANGELOG.md
src/snyk/common/proxy.ts
src/test/unit/common/proxy.test.ts

_This PR should update the `getProxyOptions` method to always respect the strictSSL VSCode config._

fix: http:proxyStrictSSL setting is respected when setting proxy options [ROAD-1132]

---

CHANGELOG.md
src/snyk/common/languageServer/languageServer.ts

_This PR should fix a Sentry exception being thrown (`Error: Channel has been closed`) by reusing the current output channel instead of creating a new one_

fix: reuse current output channel instead of disposing and creating a new one [ROAD-1226]

---

CHANGELOG.md
package.json
src/snyk/common/configuration/configuration.ts
src/snyk/common/languageServer/settings.ts
src/test/unit/common/configuration.test.ts
src/test/unit/common/languageServer/languageServer.test.ts
src/test/unit/common/languageServer/middleware.test.ts

Allow enablement of IaC scans through LS via feature flag

feat: Enable IaC scan behind preview feature flag [ROAD-1142]

---

package.json
src/snyk/common/configuration/configuration.ts
src/snyk/common/constants/settings.ts
src/snyk/common/languageServer/settings.ts

⚠️ To be merged before IaC feature flag drop.
Enables configuring IaC enablement.

feat: allow configuring IaC via settings [ROAD-1149]

---

.github/workflows/readme-sync.yaml

VS Code extension docs path has changed to https://github.com/snyk/user-docs/blob/main/docs/ide-tools/visual-studio-code-extension/README.md

fix: readme sync path

---

CHANGELOG.md
src/snyk/common/proxy.ts
src/test/unit/common/proxy.test.ts

_The `Http: Strict Proxy SSL` setting is to apply it to proxied requests only; so when no proxy is set, it should not be used to set `rejectUnauthorized`_

fix: proxyStrictSsl setting should only apply to proxied requests [ROAD-1245]

---

CHANGELOG.md
src/snyk/common/constants/languageServer.ts

This bumps the protocol version to 5. Must be merged after https://github.com/snyk/snyk-ls/pull/203

chore: update LS protocol version to 5

---

CHANGELOG.md
src/snyk/common/configuration/trustedFolders.ts
src/test/unit/common/configuration/trustedFolders.test.ts

Previously, if `/test` was trusted, `/test/folder` was not trusted in Open Source and Code scans. This is fixed with this PR.

fix: trust workspace folder if parent dir is trusted [ROAD-1250]

---

CHANGELOG.md
src/snyk/common/api/apiСlient.ts
src/snyk/common/configuration/configuration.ts
src/snyk/common/languageServer/languageServer.ts
src/snyk/common/languageServer/settings.ts
src/snyk/common/languageServer/staticLsApi.ts
src/snyk/common/proxy.ts
src/snyk/extension.ts
src/snyk/snykCode/views/issueTreeProvider.ts
src/snyk/snykOss/api/npmTestApi.ts
src/test/unit/common/languageServer/languageServer.test.ts
src/test/unit/common/languageServer/middleware.test.ts
src/test/unit/common/proxy.test.ts

Tested with https://github.com/bastiandoetsch/jvm-development-environment/. 
- provide `insecure=true` to language server when strict proxy is deactivated
- ignore invalid SSL certs if strict proxy deactivated
- use custom cert if defined via env variable and strict proxy activated
Tested:
- LS download
- Snyk API Client
- Snyk Code
- Snyk Open Source

fix: 🐛 allow unknown CAs, if strictProxy setting is deselected

---

CHANGELOG.md
src/snyk/common/constants/globalState.ts
src/snyk/common/languageServer/languageServer.ts
src/snyk/common/services/downloadService.ts
src/test/unit/common/services/downloadService.test.ts

We haven't guaranteed the update upon LSP version bump so far, that led to the following case being possible:
1. LSP version has been increased
2. Extension is released with the increased LSP version
3. Users who had LS recently updated (<4 days) wouldn't obtain the latest LS binary.

fix: ensure LS is downloaded when LSP version is bumped

---

src/snyk/common/languageServer/experiments/codeScanOrchestrator.ts
src/snyk/common/services/contextService.ts
src/test/unit/common/languageServer/experiments/codeScanOrchestrator.test.ts
src/test/unit/snykCode/codeSettings.test.ts

We currently would assume a user is always part of an experiment, which is false. We shouldn't restart LS and toggle a code scan using old implementation if user isn't.

fix: redundant ls restart, if not part of experiment [HEAD-122]

---

.github/workflows/readme-sync.yaml

To prepare for planned docs restructuring, where the docs for IDE tools will now be nested under the /integrations/ path, it's necessary to adjust the `readme-sync` workflow to ensure docs are continually synced with the README.
- ~~[ ]  Tests added and all succeed~~ Not applicable
- ~~[ ] Linted~~ Not applicable
- ~~[ ] CHANGELOG.md updated~~ Not applicable
- ~~[ ] README.md updated, if user-facing~~ Not applicable

chore: update README sync workflow

---

CHANGELOG.md
src/snyk/common/editor/codeActionsProvider.ts
src/snyk/common/messages/codeActionMessages.ts
src/snyk/common/services/productService.ts
src/snyk/extension.ts
src/snyk/snykCode/codeActions/codeIssuesActionsProvider.ts
src/snyk/snykCode/codeResult.ts
src/snyk/snykCode/codeService.ts
src/snyk/snykIac/codeActions/iacCodeActionsProvider.ts
src/snyk/snykIac/iacResult.ts
src/snyk/snykIac/iacService.ts
src/snyk/snykIac/issue.ts
src/snyk/snykIac/views/iacIssueTreeProvider.ts
src/test/unit/common/editor/codeActionsProvider.test.ts
src/test/unit/common/services/productService.test.ts
src/test/unit/snykIac/codeActions/iacCodeActionsProvider.test.ts
src/test/unit/snykIac/iacService.test.ts

- Adds IaC code actions to open an IaC issue details panel.
- Introduces base class for code actions used by Code and IaC, with Open Source to inherit from it in future.

feat: add IaC code action to open issue details panel [HEAD-148]

---

.circleci/config.yml
.gitleaksignore
.pre-commit-config.yaml

This PR adds secrets scanning to the repository. Developers should use the provided pre-commit hooks to prevent the secrets from being pushed to the repository. See https://pre-commit.com/ for details.

chore: configures secret scanning

---

.github/CODEOWNERS

Adding team Nebula as code owners for files that could break local-engine

chore: adding Nebula as GH owners [NEBULA-1290]

---

src/snyk/common/views/webviewProvider.ts
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewProvider.ts
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewScript.ts

Fixed a bug where the Snyk Learn link would sometimes not be restored when VSCode is re-opened.
For some reason the getLesson message that is posted in `WebviewProvider.checkVisibility` does not update the lesson consistently, so the state is restored in the script directly.
Also added a type for Suggestion and proper null checks

fix: Snyk Learn link missing [HEAD-558]

---

CHANGELOG.md
src/snyk/common/analytics/itly.ts
src/snyk/common/configuration/configuration.ts
src/snyk/common/error/errorReporter.ts
src/snyk/extension.ts
src/test/integration/analytics.test.ts
src/test/unit/common/analytics/itly.test.ts
src/test/unit/common/error/errorReporter.test.ts

_This PR should disable analytics and sentry events when using a fedramp endpoint._

feat: disable amplitude and sentry when using fedramp endpoints

---

CHANGELOG.md
src/snyk/common/languageServer/languageServer.ts
src/test/unit/common/languageServer/languageServer.test.ts

- always adds `language-server` as first argument to the args of the language server
- SNYK_LOG_DEVEL overrules all log level settings now
- `-d` or `--debug` in additional parameters now puts language server in debug mode

feat: add always start with `language-server` positional arg, add logging args if given [HEAD-693]

---

CHANGELOG.md
ampli.json
package.json
src/ampli/index.ts
src/snyk/common/analytics/itly.ts
src/snyk/common/commands/types.ts
src/snyk/common/configuration/configuration.ts
src/snyk/common/constants/views.ts
src/snyk/snykCode/codeSettings.ts
src/snyk/snykCode/messages/error.ts
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewScript.ts
src/test/unit/common/configuration.test.ts
src/test/unit/common/languageServer/languageServer.test.ts
src/test/unit/common/languageServer/middleware.test.ts
src/test/unit/snykCode/codeSettings.test.ts

False positives is just an empty feature flag now with analytics. It’s not used anywhere and confuses customers.

feat: remove false positives

---

package-lock.json
src/snyk/snykOss/services/vulnerabilityCount/parsers/babelParser.ts

_This PR resolves the SNYK-JS-BABELTRAVERSE-5962462 critical vulnerability by upgrading to a non-vulnerable version of @babel/traverse._

chore: Update babel/traverse package

---

src/snyk/base/modules/snykLib.ts
src/snyk/extension.ts

Calling `updateCodeSettings()` doesn't make sense before authentication.

fix: update code settings only after login

---

package.json
src/snyk/common/commands/types.ts
src/snyk/common/constants/views.ts
src/snyk/common/views/issueTreeProvider.ts
src/snyk/extension.ts
src/snyk/snykOss/interfaces.ts
src/snyk/snykOss/messages.ts
src/snyk/snykOss/ossServiceLanguageServer.ts
src/snyk/snykOss/providers/ossDetailPanelProvider.ts
src/snyk/snykOss/providers/ossVulnerabilityTreeProvider.ts
src/test/unit/snykOss/ossServiceLanguageServer.test.ts

_This PR should show OSS results in the tree view panel for OSS (LS). Results still need to be cleaned up and filtered correctly_

feat: Language Server based OSS tree view

---

CHANGELOG.md
src/snyk/common/languageServer/languageServer.ts
src/snyk/common/languageServer/middleware.ts
src/snyk/common/languageServer/settings.ts
src/test/unit/common/languageServer/languageServer.test.ts
src/test/unit/common/languageServer/middleware.test.ts
src/test/unit/common/languageServer/settings.test.ts

`LanguageClientMiddleware` includes new attributes such as `deviceId`, `integrationName`, and `integrationVersion` to align with the initialization options.
**BREAKING CHANGE**: The middleware now requires a `User` object to be instantiated.

fix: expand server settings returned by `LanguageClientMiddleware` [HEAD-975]

---

src/snyk/cli/process.ts
src/snyk/common/commands/commandController.ts
src/snyk/common/commands/types.ts
src/snyk/common/editor/codeActionsProvider.ts
src/snyk/common/languageServer/lsExecutable.ts
src/snyk/extension.ts
src/snyk/snykCode/constants/analysis.ts
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewScript.ts
src/snyk/snykIac/views/suggestion/iacSuggestionWebviewScript.ts
src/snyk/snykOss/interfaces.ts
src/snyk/snykOss/ossService.ts
src/snyk/snykOss/providers/ossCodeActionsProvider.ts
src/snyk/snykOss/providers/ossVulnerabilityCountProvider.ts
src/snyk/snykOss/providers/ossVulnerabilityTreeProvider.ts
src/test/unit/common/editor/codeActionsProvider.test.ts
src/test/unit/snykCode/codeActions/codeIssuesActionsProvider.test.ts
src/test/unit/snykIac/codeActions/iacCodeActionsProvider.test.ts
src/test/unit/snykOss/ossService.test.ts
src/test/unit/snykOss/providers/ossCodeActionsProvider.test.ts

_This PR should reintroduced the `Show the most severe vulnerability` OSS CodeAction._

fix: show most severe vulnerability code action [HEAD-1022]

---

.github/workflows/release-preview.yaml

_Updates the preview release branch to `feat/HEAD-78_oss_via_ls` so that people can test this new feature before release._

chore: change preview release branch to release OSS via LS as preview [HEAD-943]

---

src/snyk/common/commands/commandController.ts
src/snyk/snykOss/interfaces.ts
src/snyk/snykOss/providers/ossVulnerabilityTreeProvider.ts

TL;DR: This fixes the display and navigation in the custom UI for Snyk Open Source in multi-module repositories.
Previously, the folder path was assumed to be the parent directory of the package manager manifest file. This is incorrect for multi-module projects, where the opened folder is much higher in the file tree. This PR fixes this, by taking the folder path not from the issue, but from the actual folder configuration.

fix: oss with multi-module projects

---

.github/workflows/ci.yaml
.github/workflows/release-preview.yaml

_This PR reverts snyk/vscode-extension#397. We will release preview versions of the Snyk Extension when changes are made the `main` branch_

revert: change preview release branch to release OSS via LS as preview [HEAD-943]

---

src/snyk/snykCode/utils/htmlEncoder.ts
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewProvider.ts
src/test/unit/snykCode/helpers.test.ts

Previously, the encoding was done inline using `map`, which could lead to confusion due to the side effect of mutating the `lines` objects within `exampleCommitFixes`. Since `map` should ideally be used to create a new array without side effects, this was not the advised use of the method.
Screenshots attached showing that this change didn't affect the output.
|main|working branch|
|-|-|
|<img width="2047" alt="main-after" src="https://github.com/snyk/vscode-extension/assets/1948377/36b92d37-ff46-4ed5-8cde-508050608d7c">|<img width="2047" alt="refactor-after" src="https://github.com/snyk/vscode-extension/assets/1948377/e61b80b0-3171-4438-a334-40d5c6c59db1">|
|<img width="1954" alt="main-ui" src="https://github.com/snyk/vscode-extension/assets/1948377/df8ec56b-2eea-4fa6-8b11-067ce7f462a5">| …

refactor: ensure immutability to avoid side effects in HTML encoding [HEAD-1162]

---

CHANGELOG.md
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewProvider.ts
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewScript.ts

- Resolved an issue where the suggestion details section in the webview was not properly toggling visibility.
- Replaced the previous inline styling method with a CSS class.
- Implement caching for frequently accessed DOM elements.
|Before|After|
|-|-|
|<img width="1685" alt="before" src="https://github.com/snyk/vscode-extension/assets/1948377/474574d9-f95d-4842-9fc9-2b0c5d3342ed">|<img width="1686" alt="after" src="https://github.com/snyk/vscode-extension/assets/1948377/35c15b9b-a54e-4387-b72e-d7562ff0eb10">|

fix: correct visibility toggling of details section [HEAD-1172]

---

media/views/snykCode/suggestion/suggestion.scss
src/snyk/common/languageServer/types.ts
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewProvider.ts
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewScript.ts
src/snyk/snykIac/views/suggestion/iacSuggestionWebviewScript.ts
src/test/unit/common/services/learnService.test.ts

**Priority Score** is rendered dynamically within the issue details.
The **Priority Score** will become available once the **Language Server** propagates it, as detailed in this PR: https://github.com/snyk/snyk-ls/pull/425 
|Before|After|
|-|-|
|<img width="1750" alt="missing-priority-score" src="https://github.com/snyk/vscode-extension/assets/1948377/bd76dfb7-92e4-4948-b4db-f47d73aa84e0">|<img width="1750" alt="priority-score" src="https://github.com/snyk/vscode-extension/assets/1948377/faaf32ff-c20e-4d1d-9d8d-fec9e33d45aa">|
https://github.com/snyk/vscode-extension/assets/1948377/82737ccb-d86a-4ebd-97e4-67ce55b5020c

feat: display Priority Score in Snyk Code suggestions [IDE-30]

---

CHANGELOG.md
src/snyk/common/languageServer/types.ts
src/snyk/snykCode/utils/htmlEncoder.ts
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewScript.ts

This PR adds `isExampleLineEncoded` boolean property to `CommitChangeLine` type to ensure that the `htmlEncoder` function only encodes each line once, preventing double encoding on subsequent function calls.
🐛  Before
https://github.com/snyk/vscode-extension/assets/1948377/a247141d-0bdb-4c37-ab46-98b644cab940
✅ After
https://github.com/snyk/vscode-extension/assets/1948377/32642656-f031-4011-94cf-c804207b449b

fix: add flag to track encoding state of example lines

---

CHANGELOG.md
src/snyk/common/analytics/itly.ts
src/snyk/common/watchers/configurationWatcher.ts
src/snyk/extension.ts
src/test/unit/common/analytics/itly.test.ts

Fixes a bug in the analytics code where if we change the custom endpoint for analytics we don't refresh it when checking if it's permitted. So if someone were to change the custom endpoint to a FedRAMP one for example, it would still send events even if now analytics are not permitted.
Ticket: https://snyksec.atlassian.net/browse/IDE-36

fix: apply changes to custom endpoint [IDE-36]

---

.github/CODEOWNERS
catalog-info.yaml

chore: change codeowner to ide

---

.github/workflows/release-preview.yaml
.github/workflows/release-stable.yaml
CHANGELOG.md
package.json
scripts/patchPreview.js
snyk.config.json
src/snyk/common/configuration/snykConfiguration.ts
src/test/unit/common/experiment/services/experimentService.test.ts

- Removed Amplitude telemetry and corresponding setting from VSCode

fix: release workflows [IDE-155]

---

CHANGELOG.md
package.json
src/snyk/common/constants/general.ts

This PR shortens the name of the plugin to just "Snyk Security"
This change is based on multiple complaints from the field and customers.

[IDE-189] fix: shortened plugin's name to just Snyk Security

---

CHANGELOG.md
package.json
src/snyk/common/configuration/configuration.ts
src/test/unit/common/configuration.test.ts

Improves the validation so that only `http(s)://api.` APIs are configured in the custom endpoint field.
Tested manually by running the extension with the latest CLI.

fix: custom endpoint validation [IDE-126]

---

.github/workflows/readme-sync.yaml

This PR fixes synchronisation pipeline of Snyk User docs back to repository's README by fixing a folder path.

fix: synchronizing README from snyk/user-docs

---

CHANGELOG.md
src/snyk/common/configuration/configuration.ts
src/snyk/extension.ts
src/snyk/snykCode/codeSettings.ts
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewProvider.ts
src/test/unit/snykCode/codeSettings.test.ts

This PR uses the feature flag status to render Issue details provided by Language Server. 
Note: styling and template updates will be addressed in next PRs
|FF Disabled|FF Enabled|
|-|-|
|![before](https://github.com/snyk/vscode-extension/assets/1948377/b472c6e1-e782-46d4-8dfb-9dac85b638c1)|![after](https://github.com/snyk/vscode-extension/assets/1948377/9f49d80d-254a-4401-b6e3-04a2151beb8d)|

feat: conditionally render LSP template [IDE-233]

---

CHANGELOG.md
package.json

Lowers the strictness of the regex validation for the custom endpoint so that it just checks that it starts with `api` and ends with `(snyk|snykgov).io`.
Can see all the single tenant endpoints [here](https://github.com/snyk/app-ui/blob/572e96a5d9dbd5502b52c6b5861007319f7b4578/docs/runbook.md?plain=1#L34). The API endpoint for this bug can be found [here](https://github.com/snyk/polaris-instances/blob/72739d6d01bee2fcd60070c8d21f749b57b5e3c0/polaris-prod-st-morganstanley-1/backstage.yaml#L11). 
Before:
After:

fix: lower strictness of custom endpoint regex validation [IDE-352]

---

.github/workflows/release-stable.yaml

Previously, the sentry and amplitude api information was not added to the github release. Now it is.

fix: add sentry and amplitude information to github vsix [IDE-351]

---

CHANGELOG.md
media/views/snykCode/suggestion/suggestion_ls.scss
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewProvider.ts

Duplicates custom VSCode styling for the suggestion panel from `media/views/snykCode/suggestion/suggestion.scss` and injects it into the HTML after compiling `.scss` file to `.css`. This requires https://github.com/snyk/snyk-ls/pull/522 so that `${ideStyle}` is available.
To test:
- Run `make build-debug` in `snyk-ls` in the branch from https://github.com/snyk/snyk-ls/pull/522
- Run the sandbox using the debugger.
- Replace the LS path in the sandbox to the path for the local LS and disable automatically managing the binaries
- Make sure to use an org that has the `snykCodeConsistentIgnores` FF enabled (e.g. `ide-consistent-ignores-test`)
- Navigate to a Snyk Code vulnerability
https://github.com/snyk/vscode-extension/assets/81559517/9cfe6594-f997-4633-8ff2-099c3677d637

feat: load custom VSCode styling for HTML suggestion panel [IDE-240]

---

CHANGELOG.md
src/snyk/common/configuration/configuration.ts
src/snyk/common/messages/analysisMessages.ts
src/snyk/common/views/analysisTreeNodeProvider.ts
src/snyk/common/views/issueTreeProvider.ts
src/snyk/snykCode/views/securityIssueTreeProvider.ts
src/snyk/snykIac/views/iacIssueTreeProvider.ts
src/snyk/snykOss/providers/ossVulnerabilityTreeProvider.ts
src/test/integration/issueTreeProvider.test.ts

This adds some warning messages in the Tree View for the following cases:
- none of the issue view options are enabled (which implies we'd show no issues)
- we find no issues and see that we only render ignores issues
- we find no issues and see that we only render open issues
It also adds info about the number of ignored issues
Before:
- all severities selected
- some severities unselected and no vulns
- no severities selected and no vulns
- no issue view options selected
After:
- all issues are ignored
- all issues are open
- all options are disabled

feat: show message if no option is configured [IDE-332]

---

CHANGELOG.md
media/views/snykCode/suggestion/suggestionLS.scss
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewProvider.ts
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewScriptLS.ts

Adds the interactions for clicking on the Data Flow links and the inline ignore buttons at the bottom of the footer in VSCode. It duplicates some of the code in `codeSuggestionWebviewScript` but most of the code in that script right now is in `snyk-ls` since it's only HTML interactions. Eventually we can delete that file and I made a decision not to refactor it and make the two scripts use common code because it would mean more work to include the common scripts across the two.
To manually test run `npm run build` and then run the extension.
There aren't any unit tests for this code at the moment so not adding any tests.
Tickets:
- https://snyksec.atlassian.net/browse/IDE-375
- https://snyksec.atlassian.net/browse/IDE-367
https://github.com/snyk/vscode-extension/assets/81559517/00f299c7-37 …

feat: html vscode script for buttons and links [IDE-375] [IDE-367]

---

.github/workflows/ci.yaml
CHANGELOG.md
package-lock.json
package.json
src/snyk/common/configuration/configuration.ts
src/snyk/common/languageServer/settings.ts
src/test/integration/configuration.test.ts
src/test/integration/runTest.ts
src/test/unit/common/configuration.test.ts
src/test/unit/common/languageServer/middleware.test.ts
src/test/unit/common/languageServer/settings.test.ts

Changes the default auth host used when a custom endpoint is not provided so it's `https://app.snyk.io` instead of `https://snyk.io` and improves the computation logic for the URLs needed by the backend.
Re-enables the integration tests too so they run in the pipeline. They would have caught this bug before if they were enabled.
It's best to review this commit by commit.
Because of https://snyksec.atlassian.net/browse/IDE-354 it's important to restart VSCode when changing the organisation because the feature flag doesn't get updated in-between scans.
- without feature flag (stable LS)
- without custom endpoint
- with prod custom endpoint
- with dev custom endpoint
- without feature flag (newest LS)
- without custom endpoint
- with prod custom endpoint
- with dev custom endpoint
- with …

fix: default endpoint [IDE-377]

---

CHANGELOG.md
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewProvider.ts

- Use uri.fspath instead of uri.path to get local files paths.
On Mac/Linux there is no difference in the result between both but on Windows:
fspath returns: 
``'c:\\Users\\user\\work\\vscode-extension\\media\\views\\snykCode\\suggestion\\suggestionLS.css'``
path returns:
``/c:/Users/shawky/work/vscode-extension/media/views/snykCode/suggestion/suggestionLS.css``

fix: use fspath to get correct path [IDE-398]

---

CHANGELOG.md
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewProvider.ts

- use fspath instead of path.
- parse file path Uri using vscode.``vscode.Uri.file(filePath)`` instead of ``vscode.Uri.parse(filePath)``
Difference is 
```
vscode.Uri.file(filePath).fsPath
'c:\\Users\\user\\work\\project-with-vulns\\copy.ts'
vscode.Uri.parse(filePath).fsPath
'\\Users\\user\\work\\project-with-vulns\\copy.ts'
```

fix: applying AI code fixes on Windows [IDE-395]

---

CHANGELOG.md
media/views/snykCode/suggestion/suggestionLS.scss

- Added CSS rules to toggle arrow icons based on the IDE theme.
- Ensures correct arrow icon display for dark, light, and high-contrast themes.
- Related to the migration from tab-based to arrow-based navigation in Fixed Code Examples (see PR [#540](https://github.com/snyk/snyk-ls/pull/540)).
|light-high-contrast|dark-high-contrast|absyss|
|-|-|-|
|<img width="1516" alt="light-high-contrast" src="https://github.com/snyk/vscode-extension/assets/1948377/fed2ae15-4b1f-4b4d-ad0e-045b37b72866">|<img width="1516" alt="dark-high-contrast" src="https://github.com/snyk/vscode-extension/assets/1948377/0411caa3-3712-4040-9225-0bbc74fa769f">|<img width="1516" alt="absyss" src="https://github.com/snyk/vscode-extension/assets/1948377/7ebb1e01-f0bb-42cc-9905-dd6f792177eb">|

chore: add `.light-only` and `.dark-only` rules to LS CSS

---

CHANGELOG.md
src/snyk/base/modules/baseSnykModule.ts
src/snyk/base/modules/interfaces.ts
src/snyk/base/modules/snykLib.ts
src/snyk/common/services/featureFlagService.ts
src/snyk/common/watchers/configurationWatcher.ts
src/snyk/extension.ts
src/snyk/snykCode/codeSettings.ts
src/test/unit/common/services/featureFlagService.test.ts
src/test/unit/snykCode/codeSettings.test.ts

Refactors the logic used for initialising the feature flag status at startup.
To test, run the VSCode sandbox then:
- configure the organisation used in Snyk Settings to be one without `snykCodeConsistentIgnores`
- run a scan (Code at least) and open a vulnerability to see the existing suggestion panel
- restart VSCode
- configure the organisatio nused in Snyk Settings to be one with `snykCodeConsistentIgnores` (e.g. `ide-consistent-ignores-test`)
- run a scan (Code at least) and open a vulnerability to see the new suggestion panel
Note! We are aware of a bug where changing the organisation in Snyk Settings does not trigger an update of the organisation in LS and so the feature flag status doesn't change because the org hasn't, as far as the command in LS is aware.

refactor: initialisation of feature flag status [IDE-346]

---

media/views/snykCode/suggestion/suggestionLS.scss

Adds a bit more padding left and right to the number in the dataflow, so it's easier to see and matches the [designs](https://www.figma.com/design/hcI2QHUtHfcIjgrpYlMqff/Holistic-Ignores?node-id=2292-63654&t=iIxZM8o3pih8EY4M-0) more.

fix: fix padding for vscode [IDE-382] 

---

CHANGELOG.md
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewScriptLS.ts

We have to make sure to read the file-path and other attributes from the component rather than the stored `suggestion` because the suggestion doesn't have the data from the different files. 
The DataFlow section is new in VSCode so the old code didn't account for multiple files and only showed lines in the same file:
https://github.com/snyk/vscode-extension/assets/81559517/ed5ecd48-1313-414d-9067-dbbb42594759

fix: dataflow links work across files [IDE-391]

---

CHANGELOG.md
media/views/snykCode/suggestion/suggestionLS.scss

Changes some colours in order to match the [designs](https://www.figma.com/design/hcI2QHUtHfcIjgrpYlMqff/Holistic-Ignores?node-id=2292-61688&t=larzTCeHFfRtz6av-0)
Make sure to run https://github.com/snyk/snyk-ls/pull/552 first if you want to call out any inconsistent UI elements, in case they're already addressed there.

fix: colours for consistent ignores styling [IDE-386]

---

CHANGELOG.md
media/views/snykCode/suggestion/suggestion.scss

This PR fixes the issue where content within the `.suggestion` class was being overlapped by the footer. The overlap caused some content to be hidden, making it inaccessible.
**Note**:
- The height calculation (`calc(100vh - 80px)`) is based on the height of the `.suggestion-actions` element.
<video src="https://github.com/snyk/vscode-extension/assets/1948377/aa2eb42e-fb3d-444a-b53f-80437fe700ca" controls="controls" style="max-width: 460px;">
</video>
<video src="https://github.com/snyk/vscode-extension/assets/1948377/9ad70dc8-18d4-48a0-8335-bfac7ccacd62" controls="controls" style="max-width: 460px;">
</video>

fix: content within `.suggestion` is scrollable and visible [IDE-366]

---

CHANGELOG.md
src/snyk/snykOss/providers/ossDetailPanelProvider.ts

In https://github.com/snyk/snyk-ls/pull/564 we are refactoring the HTML for OSS to use `html/template` and also to eventually be able to inject styling for IntelliJ. JCEF only supports `<style>`styling and not linked stylesheets so refactoring this code to work the same way it does now for Snyk Code by injecting the `<style>` styling into the `${ideStyle}` variable.
We also won't need to inject the icons since they will be injected in the HTML template in LS.
We will deliver this version of VSCode for an older version of the CLI so we need to make sure it works with or without the changes in LS. So test it with and without https://github.com/snyk/snyk-ls/pull/564.

refactor: prepare to use the html/template version of the OSS HTML [IDE-326]

---

CHANGELOG.md
package.json
src/snyk/common/configuration/configuration.ts
src/snyk/common/constants/settings.ts
src/snyk/common/languageServer/settings.ts
src/test/unit/common/languageServer/languageServer.test.ts
src/test/unit/common/languageServer/middleware.test.ts
src/test/unit/common/languageServer/settings.test.ts

if 'use token authentication' is set to true, oauth2 authentication is disabled
depends on https://github.com/snyk/snyk-ls/pull/544

feat: add authentication setting

---

media/views/oss/suggestion/suggestion.scss
media/views/snykCode/suggestion/suggestionLS.scss
src/snyk/snykOss/providers/ossDetailPanelProvider.ts

We can remove the old ignore style for consistent Snyk Code ignores and HTML setup for OSS (base styling + injecting the stylesheet). These PRs have already been merged a while ago and contain the changes for these refactorings:
- https://github.com/snyk/snyk-ls/pull/552 for the Snyk Code ignore styling
- https://github.com/snyk/snyk-ls/pull/570 for the HTML OSS styling
- https://github.com/snyk/snyk-ls/pull/564 for the HTML OSS setup 
To test, run `npm run build` to regenerate the CSS.

refactor: removes unnecessary styling and HTML code [IDE-285] 

---

src/snyk/base/modules/snykLib.ts
src/snyk/common/constants/featureFlags.ts
src/snyk/common/services/featureFlagService.ts
src/snyk/snykCode/codeActions/codeIssuesActionsProvider.ts
src/snyk/snykCode/codeService.ts
src/test/unit/snykCode/codeActions/codeIssuesActionsProvider.test.ts

Use the new FeatureFlagService in Visual Studio Code to get snykCodeInlineIgnore FF.

feat: retrieve and store snykCodeInlineIgnore feature flag [IDE-440][IDE-441]

---

src/snyk/snykCode/views/suggestion/codeSuggestionWebviewProvider.ts
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewScript.ts
src/snyk/snykCode/views/suggestion/types.ts

This PR hides the footer with the ignore line and ignore file buttons when the feature flag exists in the settings of an organisation but is selected to `false`.
|ORG with FF Enabled|ORG with FF Disabled|
|-|-|
|<img width="1603" alt="ff-enabled" src="https://github.com/user-attachments/assets/9f831110-9c0c-473c-bed9-50153b2c6946">|<img width="1595" alt="ff-disabled" src="https://github.com/user-attachments/assets/3d21e0c7-3e89-4c7c-b173-8696d4b11e76">|

feat: toggle inline ignores button visibility based on feature flag [IDE-444]

---

package.json

This is a continuation of a work done in this PR earlier: https://github.com/snyk/vscode-extension/pull/496
The aim is to make an order of categories more logical according to usage pattern.
This is just an iteration. we will continue improving it.
There are few duplicating and possible unneeded settings left

chore: settings categories regrouped

---

src/snyk/common/configuration/configuration.ts
src/snyk/common/languageServer/settings.ts
src/test/unit/common/configuration.test.ts
src/test/unit/common/languageServer/languageServer.test.ts
src/test/unit/common/languageServer/middleware.test.ts
src/test/unit/common/languageServer/settings.test.ts

Defaults to not showing quickfixes. If Preview is enabled (see screenshot), quickfixes are added and code lenses are shown.

chore: hide oss quickfixes behind a preview flag

---

CHANGELOG.md
package.json
src/snyk/common/languageServer/settings.ts
src/snyk/common/messages/learn.ts
src/snyk/common/views/issueTreeProvider.ts
src/snyk/snykCode/views/issueTreeProvider.ts
src/snyk/snykCode/views/securityIssueTreeProvider.ts
src/snyk/snykOss/constants/messages.ts
src/snyk/snykOss/editor/editorDecorator.ts
src/snyk/snykOss/providers/ossDetailPanelProvider.ts
src/snyk/snykOss/providers/ossIssueCommandHelper.ts
src/snyk/snykOss/services/vulnerabilityCount/ossVulnerabilityCountService.ts
src/test/integration/issueTreeProvider.test.ts
src/test/unit/common/languageServer/languageServer.test.ts
src/test/unit/snykOss/providers/vulnerabilityCountProvider.test.ts

Renamed vulnerability to issue:
Removed redundant DeepCodeAI Fix tree node if no findings

fix: only display ai fix treenode if any issues, use "issue(s)" [IDE-547]

---

CHANGELOG.md
media/views/oss/suggestion/suggestion.scss

Improve readability of code elements in high-contrast themes
|Before|After|
|-|-|
|<img width="1585" alt="light-before" src="https://github.com/user-attachments/assets/d4b4e9e7-ca03-4527-835a-a706f1a70d56">|<img width="1585" alt="light-after" src="https://github.com/user-attachments/assets/432e268e-ad5b-4234-8d4f-690499ad665a">|
|<img width="1585" alt="dark-before" src="https://github.com/user-attachments/assets/003a936a-1432-42a1-aaa2-74845c74d23b">|<img width="1585" alt="dark-after" src="https://github.com/user-attachments/assets/6826cafa-c84f-4343-a105-375905f9d38e">|

fix: improve readability of code elements in high-contrast themes

---

CHANGELOG.md
src/snyk/base/services/authenticationService.ts

This PR add the missing entry in the CHANGELOG for IaC rendered via Language Server.

chore: add missing CHANGELOG IaC via LS

---

package.json

This PR removed all "experimental" notes about oauth2 authentication and makes it default.
Communications were done. This should go live on August 29.

fix: oauth2 authentication method by default

---

CHANGELOG.md
package.json
src/snyk/common/configuration/configuration.ts
src/snyk/common/constants/settings.ts
src/snyk/snykOss/providers/ossVulnerabilityTreeProvider.ts

There is now a setting in the settings page where user can select All issues, or Net new issues to do full scan or only a partial delta scan.

feat: move delta preview to settings [IDE-597]

---

package.json
src/snyk/common/constants/settings.ts

Update the Delta settings as per Figma design.
Update and move Delta settings from the “preview“ state; removed any texts containing preview, and move setting to other  scan configuration settings in the dialog.

feat: move delta preview to settings [IDE-622]

---

CHANGELOG.md
package.json
src/snyk/common/editor/codeActionsProvider.ts
src/snyk/common/languageServer/types.ts
src/snyk/common/services/productService.ts
src/snyk/common/views/analysisTreeNodeProvider.ts
src/snyk/common/views/issueTreeProvider.ts
src/snyk/snykOss/providers/ossVulnerabilityTreeProvider.ts
src/test/unit/common/services/productService.test.ts
src/test/unit/snykCode/codeService.test.ts
src/test/unit/snykIac/iacService.test.ts
src/test/unit/snykOss/ossService.test.ts

If a folder has been scanned with net new issues, and it does not contain a valid Git, then the scan returns with an error.
The change now provides a better error response indicating that the scan was done in an invalid repository. 
Old error message
New error message

fix: improve error log when git repo is faulty [IDE-657]

---

CHANGELOG.md
CONTRIBUTING.md
src/snyk/common/constants/commands.ts
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewProvider.ts
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewScript.ts
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewScriptLS.ts
src/snyk/snykCode/views/suggestion/types.ts

Add support for ai fix feedback analytic when pressing apply on a fix.

feat: send fix applied analytics

---

CHANGELOG.md
src/snyk/base/services/authenticationService.ts
src/snyk/common/languageServer/languageServer.ts
src/test/unit/base/services/authenticationService.test.ts

If $/snyk.hasAuthenticated transmits an API URL, this is saved in the settings.

feat: automated-region-configuration (IDE-732)

---

CHANGELOG.md
src/snyk/snykCode/views/suggestion/codeSuggestionWebviewScriptLS.ts

fix: hide AI fix div if no fixes [IDE-753]

---

src/snyk/snykCode/views/suggestion/codeSuggestionWebviewScriptLS.ts

Setting the `applyFix`  button to disabled after applying a certain fix.
By tracking the `lastAppliedFix` we can track, style and disable only the button corresponding to the AI Fix suggestion.
Since most of the styles were pushed to Language Server, the according style for the button can be found [there](https://github.com/snyk/snyk-ls/pull/727). 
This logic disables the button **only** for the **last applied** **suggestion** 
( eg. if we have 3 suggestions and we apply _suggestion1_ ,  apply fix button for _suggestion1_ will be **disabled**, if we then apply fix of _suggestion2_, the button of _suggestion1_ will again be **available** ( enabled ), this prevents blocking the user from experimenting with multiple suggestions. )
_Visuals that may help the reviewer. Please add screenshots …

fix: dissable button after applying fix [IDE-779]

---

package-lock.json
package.json
src/snyk/cli/cliExecutable.ts
src/snyk/common/configuration/configuration.ts
src/snyk/common/download/downloader.ts
src/snyk/common/languageServer/languageServer.ts
src/snyk/common/languageServer/middleware.ts
src/snyk/common/languageServer/settings.ts
src/snyk/common/services/downloadService.ts
src/test/unit/cli/cliExecutable.test.ts
src/test/unit/common/configuration.test.ts
src/test/unit/common/languageServer/middleware.test.ts
src/test/unit/common/languageServer/settings.test.ts

- Change default CLI download path to use XDG dirs.
- Migrate existing config for CLI path if it's in extension folder.
- revert back logic to ensure creation of CLI dir.

fix: use xdg dir as default cli Path

---

media/views/snykCode/suggestion/suggestionLS.scss

Required changes to accommodate styling from the new data-flow design and addition of data-flows to AI fixes.
Related: https://github.com/snyk/snyk-ls/pull/733

chore: add css changes needed for new ls data-flow

---

src/snyk/common/services/downloadService.ts

When the path to the CLI binary doesn't exists the checksum would fail and throw an error, not downloading the CLI, if the checksum fails we will force a download.

fix: force cli download if checksum fails

---

src/snyk/common/constants/languageServer.ts

chore: bump ls protocol version to 18

---

package.json
src/snyk/base/modules/baseSnykModule.ts
src/snyk/base/summary/authenticationService.ts
src/snyk/base/summary/summaryProviderService.ts
src/snyk/common/commands/commandController.ts
src/snyk/common/configuration/configuration.ts
src/snyk/common/constants/commands.ts
src/snyk/common/constants/languageServer.ts
src/snyk/common/constants/views.ts
src/snyk/common/languageServer/languageServer.ts
src/snyk/common/languageServer/types.ts
src/snyk/common/services/downloadService.ts
src/snyk/common/views/summaryWebviewProvider.ts
src/snyk/common/views/summaryWebviewScript.ts
src/snyk/common/watchers/configurationWatcher.ts
src/snyk/extension.ts
src/test/unit/common/languageServer/languageServer.test.ts

feat: added summary panel

---

src/snyk/base/views/supportProvider.ts

Just a change in the Help and Feedback box to be a little more internally consistent.
FROM:
TO:

Fix: Change text for help and feedback to not refer to FAQs

---

package.json

In IDEs, you can configure a custom endpoint in order to target a custom region (e.g EU). The current description for this option is "Sets API endpoint to use for Snyk requests. Useful for custom Snyk setups. E.g. https://api.eu.snyk.io/.". With the recent platform changes, on OAuth using SSO, we automatically redirect to the right instance and that field does not need to be configured anymore.
Update
`If you're using SSO (OAuth2), API endpoint configuration is automatic. Otherwise, for public regional instances, see the docs. For private instances, contact your team or account manager.`

fix: update custom endpoint description [IDE-1057]

---

src/snyk/snykCode/views/suggestion/codeSuggestionWebviewScriptLS.ts

In some cases, `event.origin` contains a URI not just the `vscode-webview://` so this caused some events such as `generateAiFix` to not be triggered, this PR handles this edge case by checking if the `event.origin` starts with `vscode-webview://`

fix: event origin check

---

src/snyk/common/proxy.ts
src/test/unit/common/proxy.test.ts

* Preserve default CAs and append custom CA to it.
* Set `ca` property at the top level of the proxy type to be recognized by axios.
- No Proxy config.
- Proxy CA is included in node env var but not trusted.
- Proxy CA is included in node env var and trusted.
- Node env var is not set but but Proxy CA is trusted.

fix: preserve default CAs and append custom certs to Axios CA options [IDE-1098]

---

src/snyk/common/llm/geminiIntegrationService.ts
src/test/unit/common/llm/geminiIntegrationService.test.ts

adds the scan source as a param to the workspace scan command when triggered via gemini code assist

feat: add scan source to workspace scan command
