snyk/vscode-extension

- package.json
- src/snyk/constants/general.ts
Change internal publishing props needed by validation process.
> chore: unify publishing properties after migrating to Snyk

- package.json
Releases feedback link, fix for "Check it out" button and writes correct Segment analytics key.
> chore: bump up the version for release

- package.json
Items to go into release:
- Iteratively integration
- Removed url & authHost settings
- Replaced help feedback title (Help Snyk and get a $100 Amazon gift card -> Help Snyk to make a better extension)
- ESLint code refactoring
> chore: release 1.0.7

- package-lock.json
- src/snyk/view/SupportProvider.ts
This PR replaces "old" DeepCode links with Snyk one.
> fix: update links in support view [ROAD-110]

- package-lock.json
- package.json
- src/snyk/lib/modules/LoginModule.ts
- src/snyk/view/IssueProvider.ts
- src/snyk/view/SupportProvider.ts
- src/snyk/view/code/qualityIssueProvider.ts
- src/snyk/view/code/securityIssueProvider.ts
- src/snyk/view/emptyTreeDataProvider.ts
- src/snyk/view/treeNode.ts
- src/snyk/view/treeNodeProvider.ts
Fixes failing authentication for users with IPv6. The main fix is in https://github.com/snyk/code-client/pull/95.
> fix: IPv6 authentication [ROAD-39]

- src/snyk/lib/analyzer/SnykAnalyzer.ts
- src/snyk/lib/modules/ReportModule.ts
- src/snyk/services/viewManagerService.ts
- src/snyk/view/code/qualityIssueProvider.ts
- src/snyk/view/code/securityIssueProvider.ts
- src/snyk/view/loadingBadge.ts
- src/test/integration/configuration.test.ts
- src/test/integration/viewNavigation.test.ts
- fix updating review results positions in code for Snyk Code quality issues
- fix broken tests
- eliminate checked todo
CI is needed as somehow my local build didn't pick up test typing issues.
> fix: tests, address todo [ROAD-189]

- package-lock.json
- package.json
- src/snyk/common/constants/general.ts
- src/snyk/common/vscodeCommandsUtils.ts
- src/snyk/extension.ts
- src/snyk/snykCode/analyzer/analyzer.ts
- src/snyk/snykCode/codeActionsProvider/ignoreCommand.ts
- src/snyk/snykCode/codeActionsProvider/issuesActionsProvider.ts
- src/snyk/snykCode/interfaces.ts
- src/snyk/snykCode/utils/analysisUtils.ts
- src/snyk/snykCode/views/issueProvider.ts
- src/snyk/snykCode/views/securityIssueProvider.ts
- src/snyk/snykCode/views/suggestionProvider.ts
- Fixes "Ignore Issue" functionality by bringing the old code back and refactoring to support Quality/Security split
- Use query for extension to direct users to extension settings from the UI
- Tooltip for running a new scan - changed re-scan to rescan
- Rename Code Security "issues" to "vulnerabilities"
> fix: "Ignore issue", Settings, cosmetic updates

- CHANGELOG.md
- package-lock.json
- package.json
* Introduced split between security and quality issues in Snyk Code.
* Ability to copy auth link to clipboard buffer during the auth process.
* Authentication for IPv6 users.
* Authentication timeout increased.
* Navigation to extension settings.
* Running extension in remote development environment.
* Marketplace links in readme.
* Removed "snyk.codeEnabled' setting as of no need.
* Updated “Help” tree view links
* Visual amends to settings view.
> chore: release 1.1.0

- package-lock.json
- package.json
- src/snyk/snykOss/views/suggestion/suggestionViewProvider.ts
- src/snyk/snykOss/views/suggestion/suggestionViewScript.ts
- src/snyk/snykOss/views/vulnerabilityProvider.ts
> feat: OSS webview tab - overview section [ROAD-289]

- src/snyk/base/modules/snykLib.ts
- src/snyk/cli/process.ts
- src/snyk/cli/services/cliService.ts
- src/snyk/snykOss/messages/treeView.ts
- src/snyk/snykOss/views/vulnerabilityProvider.ts
- fix tree when no results delivered and 0 treated as false
- add CLI process cancellation
> feat: cancel existing running OSS test, if new is issued [ROAD-303]

- .vscode/launch.json
- package-lock.json
- package.json
- src/snyk/base/modules/loginModule.ts
- src/snyk/base/modules/reportModule.ts
- src/snyk/common/watchers/filesWatcher.ts
- src/snyk/snykCode/analyzer/analyzer.ts
- src/snyk/snykCode/analyzer/progress.ts
- src/snyk/snykCode/code.ts
- src/snyk/snykCode/interfaces.ts
- src/snyk/snykCode/utils/analysisUtils.ts
- src/snyk/snykCode/views/suggestionProvider.ts
- new Code API support with legacy json format 
- disabled feedback form while it's broken anyway
> feat: new Code API support, disabled feedback form [ROAD-311]

- CHANGELOG.md
- package-lock.json
- package.json
Provide feedback that we experience some technical difficulties until we fix the root cause.
> chore: release 1.1.3

- .github/workflows/ci.yaml
- .itlyrc
- ampli.json
- package-lock.json
- package.json
- src/ampli/index.ts
- src/snyk/common/analytics/itly.ts
- src/snyk/common/analytics/itlyErrorPlugin.ts
- src/test/integration/analytics.test.ts
Example switch was done in registry, see this https://github.com/snyk/registry/pull/24177.
> feat: switch to Ampli from Itly CLI [ROAD-458]

- package-lock.json
- package.json
Bumped version of @snyk/code-client that should help tolerating network issues.
Related ticket in Snyk code : https://snyksec.atlassian.net/browse/COD-571
> fix: updated code-client version improved network outage tolerance

- package-lock.json
- package.json
- src/snyk/base/messages/snykMessages.ts
- src/snyk/base/modules/snykLib.ts
- src/snyk/cli/services/cliService.ts
- src/snyk/extension.ts
- src/snyk/snykOss/services/ossService.ts
- src/snyk/snykOss/views/ossVulnerabilityTreeProvider.ts
> feat: show CLI download error in tree [ROAD-461]

- CHANGELOG.md
- package-lock.json
- package.json
- Use standard VS Code buttons for ignoring Snyk Code suggestions in webview.
- Improved network outage tolerance for Snyk Code requests.
- Feedback link updated.
- Surface vulnerability count from OSS scan in editor for JavaScript and TypeScript files.
- Surface vulnerability count from OSS scan in editor for package.json for NPM projects.
- Surface imported modules as part of `<script>` element in editor for HTML files.
- Retry CLI download when CLI is not installed correctly and scan is requested.
- Show CLI download failure within the Open Source Security tree view.
- Ability to run A/B experiments using Amplitude Experiment.
- Commit comments as part of Snyk Code suggestion view.
> chore: release 1.2.2

- src/snyk/common/commands/commandController.ts
- src/snyk/snykCode/interfaces.ts
Static typing fixes further issue reoccurring, thus no additional test added :-) 
Possibly also fixes #43
> fix: prevent mutation that causes Code webview crash [ROAD-460]

- CHANGELOG.md
- package-lock.json
- package.json
- Use user environment settings when spawning Snyk CLI as a child process.
- Snyk Code 'Show this suggestion' quick fix not opening the view from an editor.
- Snyk Code suggestion view not displaying when navigating multiple times to the same issue.
> chore: release 1.2.4

- package-lock.json
- package.json
This PR also updates `package-lock.json` that was committed with the wrong NPM version in https://github.com/snyk/vscode-extension/pull/118.
> feat: update the experiment welcome view with Log4Shell [ROAD-614]

- README.md
- Update readme with Log4Shell CVE ID and link to Vulnerability Database
- Add reference link to exploit maturity
> chore: update readme with Log4Shell CVE link

- README.md
> chore: update documentation [ROAD-631]

- src/snyk/cli/process.ts
- src/snyk/cli/services/cliService.ts
- src/snyk/snykOss/services/ossService.ts
- src/test/unit/cli/services/cliService.test.ts
> fix: missing cwd for CLI arguments that rely on it [ROAD-635]

- src/snyk/snykCode/views/suggestion/codeSuggestionWebviewProvider.ts
It seems that the problem stems from missing disposal for the registered serialiser. Has been confirmed in test by @deepcodeg.
> fix: empty state [ROAD-605]

- CHANGELOG.md
- package-lock.json
- package.json
- src/snyk/common/services/cliConfigService.ts
- src/snyk/snykCode/codeSettings.ts
- src/test/unit/common/services/cliConfigService.test.ts
This PR adds a feature to check SAST API endpoint with organization from settings (if configured).
> feat: sast settings with organization as url query param [ROAD-734]

- CHANGELOG.md
- README.md
- package.json
- src/snyk/common/constants/general.ts
Renaming it to Snyk Security - Code and Open Source Dependencies
> refactor: rename snyk vulnerability scanner display name

- .github/workflows/release-stable.yaml
- Reordering the stable release steps for CD pipeline
> fix: stable release order

- package-lock.json
- src/snyk/common/configuration/configuration.ts
- src/snyk/common/constants/settings.ts
Reference: https://sentry.io/share/issue/afcc8229002b4264950d9c7b225189ab/
> fix: Unable to write to User Settings

- src/test/unit/base/services/authenticationService.test.ts
> test: add tests for setToken method [ROAD-819]

- .github/workflows/release-stable.yaml
Separating the release steps from publish steps for the automated release so we can build a better repeatable process for releasing.
> fix: separating the release steps from publish

- src/snyk/common/error/errorReporter.ts
- src/snyk/snykCode/error/snykCodeErrorHandler.ts
- src/test/unit/snykCode/error/snykCodeErrorHandler.test.ts
Capturing the Snyk code error response correctly and fixing the `code_request_id` reporting. 
> fix: code api error response reporting [ROAD-867]

- CHANGELOG.md
- README.md
- package.json
Updates org setting tooltip text to clarify possible values. Snyk docs link updated accordingly. Was reviewed by Andy.
> feat: add org slug description docs [ROAD-817]

- CHANGELOG.md
Adds changelog entry for #174.
> docs: update changelog with devDependencies OS contribution

- CHANGELOG.md
- package-lock.json
- package.json
Fixes Marketplace timed out release by pushing to the new version.
> fix: Marketplace timed out release

- .github/workflows/release-stable.yaml
Fixes https://github.com/snyk/vscode-extension/runs/6090020533?check_suite_focus=true
> fix: fix "release" step from release-stable workflow

- .github/workflows/release-stable.yaml
- CHANGELOG.md
- package-lock.json
- package.json
- src/snyk/common/commands/commandController.ts
Fixes wrong scope binding when "Set Token" command gets issued. No tests added, since this will be an integration test that we don't support so far.
> fix: set token command [ROAD-896]

- .github/workflows/readme-sync.yaml
- src/snyk/common/analytics/itly.ts
Workflow that synchronises readme.md from Snyk Docs. Copied from Snyk CLI - https://github.com/snyk/cli/blob/95f7e1021c817a44d4018c4f518061d69f6dbb5b/.github/workflows/sync-cli-help-to-user-docs.yml
> feat: synchronise Readme from Snyk Docs [ROAD-775]

- CHANGELOG.md
- package-lock.json
- package.json
- src/snyk/snykCode/codeService.ts
This PR enables base64 file content encoding for Snyk Code analysis.
> feat: encode code content [ROAD-909]

- CHANGELOG.md
- package.json
Adds links to privacy policy and terms of service.
**Old**
**New**
> feat: add links to privacy policy and terms of service (ROAD-840)

- CHANGELOG.md
- src/snyk/common/error/errorReporter.ts
- src/snyk/common/user.ts
- src/test/unit/common/user.test.ts
Reports anonymised user ids to Sentry.
> feat: report anonymised user id to Sentry (ROAD-884)

- CHANGELOG.md
- media/views/common/webview.scss
- src/snyk/snykCode/views/suggestion/codeSuggestionWebviewProvider.ts
- src/snyk/snykCode/views/suggestion/codeSuggestionWebviewScript.ts
Don't show example fixes for Snyk code issues if there aren't any.
Show an info instead: There are no example fixes for this issue.
> fix: Don't show example fixes if there are none.

- src/snyk/cli/messages/messages.ts
Replace references to CLI with "plugin dependencies"
[ROAD-1024]
[ROAD-1024]: https://snyksec.atlassian.net/browse/ROAD-1024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: improve user-visible messages when downloading the CLI

- CHANGELOG.md
- ampli.json
- package.json
- src/ampli/index.ts
- src/snyk/base/modules/baseSnykModule.ts
- src/snyk/base/services/scanModeService.ts
- src/snyk/common/analytics/itly.ts
- src/snyk/common/commands/commandController.ts
- src/snyk/extension.ts
- src/snyk/snykCode/constants/modes.ts
- src/test/unit/base/services/scanModeService.test.ts
Introduce analytics around Snyk Code scanning modes.
> feat: track scanning modes switch [ROAD-1030]

- .github/workflows/readme-sync.yaml
Enable automatic signing commits issued by actions bot for readme sync.
Example PR: https://github.com/snyk/vscode-extension/pull/264
> feat: sign commits issued from GitHub Actions bot [ROAD-931]

- CHANGELOG.md
- ampli.json
- src/ampli/index.ts
- src/snyk/common/analytics/itly.ts
- src/snyk/common/services/notificationService.ts
- src/test/unit/common/services/notificationService.test.ts
Introduce analytics around Open Source scan reminder notification.
> feat: track OSS scan notification and button clicks [ROAD-1031]

- CHANGELOG.md
- package-lock.json
- package.json
- src/snyk/snykCode/error/snykCodeErrorHandler.ts
- src/test/unit/snykCode/error/snykCodeErrorHandler.test.ts
Patches #260 to work correctly.
> fix: mark Code API 404 as retryable [ROAD-1037]

- package.json
_This PR updates wording for sending crash reports and analytics to be consistent across all our supported IDEs_
> chore: updated wording for collecting analytics and sending crash reports

- CHANGELOG.md
- package-lock.json
- package.json
- src/snyk/snykCode/error/snykCodeErrorHandler.ts
> fix: Snyk Code 404's [ZEN-262]

- .github/workflows/readme-sync.yaml
Fixes Snyk Docs synchronisation.
> fix: readme sync [ROAD-1104]

- .github/workflows/ci.yaml
- .github/workflows/release-preview.yaml
- .github/workflows/release-stable.yaml
_This PR updates the `release-stable.yaml`'s `Build and Release` workflow so that it will update the `package.json` version to match the current Github tag. This means that the version `package.json` is no longer required to be manually maintained._
> Feat/sync release versions [ROAD-1077]

- CHANGELOG.md
- src/snyk/common/configuration/configuration.ts
- src/test/unit/common/configuration.test.ts
_As an engineer interested in using a standalone LS binary, I want to be able to provide a path to binary. This PR will add a required env var `SNYK_LS_PATH` to achieve this._
> feat: SNYK_LS_PATH var is now required [ROAD-1050]

- CHANGELOG.md
- src/snyk/base/services/authenticationService.ts
- src/snyk/common/languageServer/languageServer.ts
- src/snyk/extension.ts
- src/test/unit/base/services/authenticationService.test.ts
- src/test/unit/common/languageServer/languageServer.test.ts
_This PR implements handling of the `$/snyk.hasAuthenticated` notification._
> feat: Implementing handle LS auth notification [ROAD-1045]

- package.json
- src/snyk/common/commands/commandController.ts
- src/snyk/common/constants/commands.ts
- src/snyk/common/constants/views.ts
- src/snyk/common/languageServer/languageServer.ts
- src/snyk/common/languageServer/settings.ts
- src/snyk/extension.ts
- src/test/unit/common/languageServer/languageServer.test.ts
Set LS to not automatically authenticate when a scan starts
> feat: Set automaticAuthentication to false [ROAD-1043]

- CHANGELOG.md
- package-lock.json
- package.json
- src/snyk/common/languageServer/languageServer.ts
Fixes https://sentry.io/organizations/snyk/issues/3692749039/?environment=production&project=5973186
> fix: language client dependency error

- CHANGELOG.md
- package-lock.json
- package.json
- src/snyk/common/languageServer/languageServer.ts
Fixes "Language client is not ready yet when handling" error by reverting previous commit.
> fix: Language client is not ready yet when handling

- CHANGELOG.md
- package-lock.json
- package.json
- src/snyk/common/languageServer/languageServer.ts
- src/test/unit/common/languageServer/languageServer.test.ts
Correctly fixes https://sentry.io/organizations/snyk/issues/3692749039/?environment=production&project=5973186, ensuring language server is ready before subscribing to notifications.
> fix: language client vs code requirement

- src/snyk/common/constants/languageServer.ts
- src/snyk/extension.ts
Enable full scans using both client and server.
> feat: allow full scan with Language Server [ROAD-1144]

- CHANGELOG.md
- package.json
- src/snyk/base/modules/snykLib.ts
- src/snyk/cli/services/cliService.ts
- src/snyk/common/commands/commandController.ts
- src/snyk/common/configuration/configuration.ts
- src/snyk/common/configuration/trustedFolders.ts
- src/snyk/common/constants/languageServer.ts
- src/snyk/common/constants/settings.ts
- src/snyk/common/languageServer/languageServer.ts
- src/snyk/common/languageServer/settings.ts
- src/snyk/common/messages/analysisMessages.ts
- src/snyk/common/views/analysisTreeNodeProvider.ts
- src/snyk/common/watchers/configurationWatcher.ts
- src/snyk/snykCode/codeService.ts
- src/snyk/snykCode/views/issueTreeProvider.ts
- src/snyk/snykOss/services/ossService.ts
- src/snyk/snykOss/views/ossVulnerabilityTreeProvider.ts
- src/test/unit/cli/services/cliService.test.ts
- src/test/unit/common/configuration/trustedFolders.test.ts
- src/test/unit/common/languageServer/languageServer.test.ts
- src/test/unit/common/languageServer/middleware.test.ts
- src/test/unit/snykOss/services/ossService.test.ts
Adds workspace trust mechanism to ensure scans are run on the trusted folders.
> feat: workspace trust

- src/snyk/common/constants/languageServer.ts
Increases LSP version to customers download the correct LS version with trust gate functionality.
> chore: bump lsp version for trust gate

- CHANGELOG.md
- src/snyk/common/languageServer/settings.ts
- src/snyk/snykCode/analyzer/analyzer.ts
- src/test/unit/common/languageServer/languageServer.test.ts
- src/test/unit/common/languageServer/middleware.test.ts
_This PR should manage severity filtering in LS._
> feat: manage severity filtering in LS [ROAD-1143]

- CHANGELOG.md
- package.json
- src/snyk/base/services/authenticationService.ts
- src/snyk/common/configuration/configuration.ts
- src/snyk/common/constants/general.ts
- src/snyk/common/languageServer/languageServer.ts
- src/snyk/common/languageServer/settings.ts
- src/test/unit/common/configuration.test.ts
- src/test/unit/common/languageServer/languageServer.test.ts
- src/test/unit/common/languageServer/middleware.test.ts
- src/test/unit/mocks/configuration.mock.ts
- Drops feature flag for IaC scans.
- Updates extension title
> feat: release IaC publicly [ROAD-1180]

- package.json
Adds new keywords to assist in extension finding on Marketplace.
https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner
> feat: add new keywords

- package-lock.json
- package.json
- src/snyk/common/languageServer/settings.ts
- src/test/unit/common/languageServer/languageServer.test.ts
- src/test/unit/common/languageServer/middleware.test.ts
> feat: separate config for snyk code security and snyk code quality in LS settings

- CHANGELOG.md
- src/snyk/base/views/supportProvider.ts
Fixes contact and docs url.
Ref: https://snyk.slack.com/archives/C01M63AMWD6/p1672776901194249
> fix: feedback url & docs link

- package-lock.json
- package.json
Signed-off-by: Bastian Doetsch <bastian.doetsch@snyk.io>
> fix: updated amplitude/ampli to ^1.29.0

- CHANGELOG.md
- src/snyk/common/commands/commandController.ts
- src/snyk/common/commands/types.ts
- src/snyk/common/constants/views.ts
- src/snyk/common/languageServer/languageServer.ts
- src/snyk/common/languageServer/types.ts
- src/snyk/common/services/viewManagerService.ts
- src/snyk/common/views/treeNode.ts
- src/snyk/common/vscode/window.ts
- src/snyk/extension.ts
- src/snyk/snykCode/codeActions/issuesActionsProvider.ts
- src/snyk/snykCode/codeService.ts
- src/snyk/snykCode/codeServiceOld.ts
- src/snyk/snykCode/interfaces.ts
- src/snyk/snykCode/utils/issueUtils.ts
- src/snyk/snykCode/views/interfaces.ts
- src/snyk/snykCode/views/issueTreeProvider.ts
- src/snyk/snykCode/views/issueTreeProviderOld.ts
- src/snyk/snykCode/views/qualityIssueTreeProvider.ts
- src/snyk/snykCode/views/securityIssueTreeProvider.ts
- src/snyk/snykCode/views/suggestion/codeSuggestionWebviewProvider.ts
- src/snyk/snykCode/views/suggestion/codeSuggestionWebviewProviderOld.ts
- src/snyk/snykCode/views/suggestion/codeSuggestionWebviewScript.ts
- src/test/unit/common/commands/commandController.test.ts
- src/test/unit/common/services/learnService.test.ts
- src/test/unit/mocks/window.mock.ts
- src/test/unit/snykCode/codeService.test.ts
This PR enables:
- Filling tree view with results from LS request
- Populating details panel for certain reported issue
- Ignoring issue inline per line or per file
The following elements will be addressed in the subsequent PRs:
- Ignore code actions
- Opening details panel from code action
> feat: tree view and details panel for Code results from LS [HEAD-10]

- src/snyk/common/commands/commandController.ts
- src/snyk/common/commands/types.ts
- src/snyk/common/languageServer/languageServer.ts
- src/snyk/common/languageServer/types.ts
- src/snyk/common/services/learnService.ts
- src/snyk/extension.ts
- src/snyk/snykCode/codeService.ts
- src/snyk/snykCode/views/issueTreeProvider.ts
- src/snyk/snykCode/views/suggestion/codeSuggestionWebviewProvider.ts
- src/snyk/snykCode/views/suggestion/codeSuggestionWebviewScript.ts
- src/test/unit/common/commands/commandController.test.ts
- src/test/unit/common/services/learnService.test.ts
- src/test/unit/mocks/languageServer.mock.ts
- src/test/unit/snykCode/codeService.test.ts
- Enables links to Snyk Learn in new Code webview header.
- Fixes opening output channel when Snyk Code results in an error.
> feat: enable Snyk Learn in new Code webview [HEAD-11]

- CHANGELOG.md
- src/snyk/common/constants/languageServer.ts
> fix: reduce load on Snyk Code API [HEAD-122]

- package-lock.json
- package.json
- src/snyk/snykCode/codeServiceOld.ts
There were 2 problems:
1. not setting org name properly. This caused problems for users, that belong to multiple organizations with different settings
2. extendAnalysis was not passing analysisContext at all, thus misleading our logs 
> fix: old Code Service logic: providing proper "analysisContext"

- CHANGELOG.md
- README.md
- src/snyk/common/languageServer/types.ts
_This PR should add type definitions for the IaC scan feature._
> feat: defining interfaces for IaC [HEAD-146]

- CHANGELOG.md
- package.json
- src/snyk/common/configuration/configuration.ts
- src/test/unit/common/configuration.test.ts
_This PR should add a feature flag for IaC UI._
> feat: adds IaC UI feature flag [HEAD-152]

- src/snyk/common/vscode/window.ts
- src/snyk/snykCode/views/suggestion/codeSuggestionWebviewProvider.ts
- src/snyk/snykCode/views/suggestion/codeSuggestionWebviewProviderOld.ts
Fixed document opening when using windows paths.
> fix: file opening on windows [HEAD-168]

- CHANGELOG.md
- src/snyk/snykIac/views/suggestion/iacSuggestionWebviewProvider.ts
- src/snyk/snykIac/views/suggestion/iacSuggestionWebviewScript.ts
Add details panel body for IaC.
> feat: add details panel body for IaC

- src/snyk/common/views/issueTreeProvider.ts
- src/snyk/snykCode/views/issueTreeProvider.ts
- src/snyk/snykIac/views/iacIssueTreeProvider.ts
Fix iac issue tree without any elements when scan is running.
> fix: iac issue tree 

- CHANGELOG.md
- package.json
- src/snyk/common/configuration/configuration.ts
- src/snyk/common/constants/views.ts
- src/snyk/common/services/contextService.ts
- src/snyk/extension.ts
- src/snyk/snykIac/views/suggestion/iacSuggestionWebviewScript.ts
- src/test/unit/common/configuration.test.ts
Remove feature flag.
Fix navigation for references.
> feat: remove feature flag

- src/snyk/common/constants/languageServer.ts
In order to receive further updates in LS, the protocol version must be bumped to the latest (`8`)
> chore: update LS protocol version

- CHANGELOG.md
- src/snyk/common/constants/languageServer.ts
Ensures extension can show Autofix enabled in the latest Snyk LSP version
> feat: bump protocol to version with Autofix enabled

- CHANGELOG.md
- README.md
- package.json
_This PR should update the support links in the README and on the marketplace's `Issues` link._
> fix: update support links

- src/snyk/snykCode/views/suggestion/codeSuggestionWebviewProvider.ts
Fixed the ignore button on Snyk Code issues when using Windows
> [HEAD-330] fix: Ignore button in Windows

- package.json
- src/snyk/snykCode/codeSettings.ts
- src/test/unit/snykCode/codeSettings.test.ts
Enables Snyk Code views if Snyk Code Local Engine is enabled
> feat: enabling Snyk Code Local Engine

- package.json
This PR covers what wasn't included in #364 to enable local engine
> fix: removed local-engine flags in SAST view condition

- src/snyk/base/modules/snykLib.ts
- src/snyk/common/commands/commandController.ts
- src/snyk/common/configuration/configuration.ts
- src/snyk/extension.ts
- src/test/unit/common/configuration.test.ts
* Run initial scan only after starting language server
* Minor logging improvement
* Remove usage of isDevelopment
> chore: minor startup improvement

- CHANGELOG.md
- package-lock.json
_This PR updates transitive dependencies stuck on vulnerable versions due to package-lock drift._
> fix: package-lock drift causing transitive vulnerabilities

- src/snyk/common/types.ts
- src/snyk/extension.ts
- src/snyk/snykOss/constants/messages.ts
- src/snyk/snykOss/editor/editorDecorator.ts
- src/snyk/snykOss/providers/ossVulnerabilityCountProvider.ts
- src/snyk/snykOss/providers/vulnerabilityCountProvider.ts
- src/snyk/snykOss/services/vulnerabilityCount/ossVulnerabilityCountService.ts
- src/test/unit/snykOss/providers/vulnerabilityCountProvider.test.ts
- src/test/unit/snykOss/services/vulnerabilityCount/ossVulnerabilityCountService.test.ts
_This PR should switch to LS for vuln count and cleanup some redundant code._
> fix: vulnerability count message [HEAD-1024]

- package.json
Use clearer phrasing to explain how to get slugname.
> chore: use clearer phrasing on how to get slugname

- CHANGELOG.md
- src/snyk/snykOss/editor/editorDecorator.ts
_This PR should omit the vulnerability count text when the vuln count is 0_
> fix: cleaner vuln count text [HEAD-1063]

- package-lock.json
- package.json
This PR aggregates **minor** dependencies updates from:
- #413 
- #414
- #415
HEAD-1163
> chore: dependencies update [HEAD-1163 ]

- CHANGELOG.md
- README.md
This PR updates the links in the `README.md` file, correcting them to point to the appropriate Visual Studio Code extension documentation pages. The original links incorrectly pointed to the Visual Studio extension documentation.
- Updated URLs in the README.md to direct users to the correct Visual Studio Code extension documentation pages.
- Adjusted the link text from "Visual Studio extension" to "Visual Studio Code extension" to correctly reflect the content of the linked pages.
- All updated URLs have been manually checked to ensure they are valid and direct users to the correct documentation pages.
- The textual changes have been reviewed for clarity and accuracy in referencing the Visual Studio Code extension.
- These changes improve the accuracy and usefulness of the `README.md` …
> fix: update README.md to correct Visual Studio Code extension links

- .github/workflows/ci.yaml
> fix: remove iteratively secret from build workflow [IDE-155]

- CHANGELOG.md
- package.json
> fix: do not restrict activation of extension [HEAD2-48]

- CHANGELOG.md
- src/snyk/common/languageServer/types.ts
- src/snyk/snykCode/views/issueTreeProvider.ts
- src/test/unit/common/services/learnService.test.ts
Added the [ Ignored ] text if the finding should be marked as ignored.
> feat: mark findings as ignored in tree view IDE-213

- CHANGELOG.md
- src/snyk/common/constants/languageServer.ts
This requires https://github.com/snyk/snyk-ls/pull/485 to be merged & released first.
> chore: bump LS Protocol version to 11 [IDE-236]

- CHANGELOG.md
- src/snyk/common/constants/languageServer.ts
Make latest language server version available.
> chore: update protocol version to 12

- CHANGELOG.md
- src/snyk/extension.ts
- src/snyk/snykCode/views/suggestion/codeSuggestionWebviewProvider.ts
Further fixes for AI "Apply fix" flow on Windows
> fix: use fspath instead of path [IDE-410]

- CONTRIBUTING.md
This is just a cleanup, as our repository is showed up in a search by code-client
https://github.com/search?q=org%3Asnyk%20%22%40snyk%2Fcode-client%22&type=code
> chore: updated CONTRIBUTING doc, removed @snyk/code-client

- .circleci/config.yml
> chore: add quality gates

- CHANGELOG.md
- src/snyk/common/languageServer/settings.ts
- src/test/unit/common/languageServer/languageServer.test.ts
> feat: transmit required protocol version

- .github/workflows/readme-sync.yaml
> fix: sync source for readme

- CHANGELOG.md
- package.json
- src/snyk/common/configuration/configuration.ts
- src/snyk/common/constants/settings.ts
- src/snyk/common/languageServer/settings.ts
- src/test/unit/common/languageServer/languageServer.test.ts
- src/test/unit/common/languageServer/middleware.test.ts
- src/test/unit/common/languageServer/settings.test.ts
This reverts commit f066c29117d55821d42357ad85ec81a22523af6a. 
This is temporary until we have dealt with potential OAuth2 issues.
> Revert "feat: add authentication setting (#487)"

- src/snyk/snykCode/codeActions/codeIssuesActionsProvider.ts
- src/test/unit/snykCode/codeActions/codeIssuesActionsProvider.test.ts
Hides the ignore in file inline ignore action if feature flag is turned off.
> feat: hide ignore action if feature flag is off [IDE-508]

- package.json
- src/snyk/common/configuration/configuration.ts
> fix: add spaces to value selection for delta

- package.json
- src/snyk/common/constants/settings.ts
This is a tiny PR, to adjust naming of the setting, that controls the new experimental Delta findings feature
> chore: renamed "Known issues" to "All issues" in the setting for delta findings

- package.json
- src/snyk/common/configuration/configuration.ts
- src/snyk/common/constants/settings.ts
- src/snyk/common/constants/views.ts
- src/snyk/common/watchers/configurationWatcher.ts
- src/snyk/extension.ts
- Remove the panel previously added with "Code Scan - New Issues" 
- fix a bug with refreshing the UI on config change for delta.
- Moved delta setting back to preview.
> fix: refresh views when changing config [IDE-516]

- package.json
> fix: use token as default auth

- CHANGELOG.md
- src/snyk/common/constants/languageServer.ts
- src/snyk/common/languageServer/types.ts
- src/snyk/common/services/diagnosticsService.ts
- src/snyk/common/services/productService.ts
- src/snyk/extension.ts
- src/snyk/snykCode/codeService.ts
- src/snyk/snykIac/iacService.ts
- src/snyk/snykOss/ossService.ts
- src/test/unit/common/languageServer/languageServer.test.ts
- src/test/unit/common/services/productService.test.ts
- src/test/unit/snykCode/codeService.test.ts
- src/test/unit/snykIac/iacService.test.ts
- src/test/unit/snykOss/ossService.test.ts
- Get issue list from VS Code API Diagnostics instead of snyk.scan.
- Bump LS Version to 14.
> refactor: use issues from diagnostics [IDE-538]

- package-lock.json
- package.json
- src/snyk/common/languageServer/types.ts
- src/snyk/snykIac/views/suggestion/iacSuggestionWebviewProvider.ts
- src/snyk/snykIac/views/suggestion/iacSuggestionWebviewScript.ts
This PR renders IaC via Language Server!
Needs: https://github.com/snyk/snyk-ls/pull/616 which was already merged 💪 
|Before|After|
|-|-|
|<img width="1591" alt="iac-before" src="https://github.com/user-attachments/assets/b07aa90d-4cc5-40c9-97c4-78647bed1b31">|<img width="1635" alt="iac-after" src="https://github.com/user-attachments/assets/cb9e5249-b9d8-4fd4-b6ed-0f1fc4da9609">|
> feat: IaC via Language Server

- CHANGELOG.md
- src/snyk/common/views/issueTreeProvider.ts
- src/snyk/snykOss/providers/ossVulnerabilityTreeProvider.ts
This change adds base branch selection tree node to OSS and IaC trees.
> feat: base branch selection for OSS and IaC

- package-lock.json
- package.json
This PR updated Axios from `1.7.3` to `1.7.4`
> chore: update axios

- .github/workflows/readme-sync.yaml
Our synchronization script is broken due to folder rename
This PR fixes this problem.
> chore: fixed docs sync script by fixing a path

- .github/workflows/release-stable.yaml
As we are going to align our stable releases with the CLI schedule, this is a first step to disable automated weekly release.
> chore: modified Github action to release new stable versions manually

- package.json
- src/snyk/common/constants/settings.ts
Update Visual Studio Code settings for Net new issues to correspond to Figma
> chore: update UI to correspond to design [IDE-614]

- src/snyk/common/languageServer/staticLsApi.ts
> chore: change cli download url

- src/snyk/common/languageServer/staticLsApi.ts
Reverts snyk/vscode-extension#531
> Revert "chore: change cli download url"

- .github/workflows/release-stable.yaml
- CHANGELOG.md
- src/snyk/common/constants/languageServer.ts
- src/test/unit/common/languageServer/languageServer.test.ts
> fix: update protocol version to 15

- package.json
> fix: delete duplicate setting for delta

- src/snyk/common/constants/languageServer.ts
- src/test/unit/common/languageServer/languageServer.test.ts
> chore: bump ls protocol version to 16

- package.json
fixed description for the new Delta findings setting
> fix: fixed description for the new Delta findings setting

- CHANGELOG.md
- media/views/oss/suggestion/suggestion.scss
> fix: oss font size

- CHANGELOG.md
- src/snyk/common/languageServer/staticLsApi.ts
> fix: update download endpoint

- CHANGELOG.md
- src/snyk/snykCode/views/suggestion/codeSuggestionWebviewScriptLS.ts
> fix: send correct fixid  [IDE-754]

- src/snyk/common/views/summaryWebviewProvider.ts
> fix: replace ideScript

- src/snyk/common/views/issueTreeProvider.ts
> fix: tree items order

- src/snyk/common/views/issueTreeProvider.ts
- src/snyk/snykOss/providers/ossVulnerabilityTreeProvider.ts
Previously `snyk:` URIs with `action=showInDetailPanel` and `product=Snyk+Open+Source` were not working correctly. This fixes that.
> fix: show OSS issues for the snyk URI

- src/snyk/common/languageServer/middleware.ts
> fix: decode document uri before parsing

- src/snyk/common/llm/geminiIntegrationService.ts
> fix: display error message, if we cannot parse the prompt, correct command description

- src/snyk/common/llm/geminiIntegrationService.ts
- changes tool id to `Snyk` from `snyk`
- removes pushing scan progress to output stream
> chore: deactivate some messages in gemini

- media/views/scanSummary/ScanSummaryInit.html
The spinner is displayed while waiting for the LS to load.
This file is unused by VS Code, but I have kept it in sync with the other IDEs.
- N/A - Couldn't see a linter for HTML/CSS
- N/A
- N/A
> fix: Unsquish the loading spinner [IDE-1101]

- src/snyk/common/languageServer/languageServer.ts
- src/snyk/common/llm/geminiIntegrationService.ts
> fix: remove mcp notification

- src/snyk/common/constants/languageServer.ts
> chore: bump LS protocol version

- src/snyk/common/configuration/configuration.ts
- src/snyk/common/configuration/folderConfigs.ts
- src/snyk/common/languageServer/languageServer.ts
- src/snyk/common/languageServer/settings.ts
- src/snyk/common/proxy.ts
- src/test/unit/common/proxy.test.ts
> fix: ensure didChangeConfiguration sends correct folderConfig

- src/snyk/base/modules/snykLib.ts
- src/snyk/common/llm/geminiIntegrationService.ts
- src/test/unit/common/llm/geminiIntegrationService.test.ts
> fix: scan source

- src/snyk/common/constants/commands.ts
- src/snyk/snykCode/views/suggestion/codeSuggestionWebviewProvider.ts
- src/snyk/snykCode/views/suggestion/ideFuncs/ideSubmitIgnoreRequest.ts
- src/snyk/snykCode/views/suggestion/types.ts
Handle the values from the JS provided by LS and call the `snyk.submitIgnoreRequest` LS command.
- No, no one else has done any, plus the logic is simple.
- No, the feature is going to be released as EA first.
- No, the feature is going to be released as EA first.
> feat: handle IAW creation form [IDE-1075]

- RELEASE.md
Added a release.md describing the release process steps.
> docs: add release document [IDE-1224]

- src/snyk/common/constants/languageServer.ts
- src/snyk/common/languageServer/types.ts
- src/snyk/common/services/diagnosticsService.ts
- src/snyk/common/services/productService.ts
- src/snyk/snykCode/views/suggestion/codeSuggestionWebviewProvider.ts
- src/test/unit/common/services/learnService.test.ts
- src/test/unit/common/services/productService.test.ts
- src/test/unit/mocks/issue.mock.ts
> fix: fetch results by folderName from diagnostics [IDE-1045]

- package.json
- src/snyk/extension.ts
> feat: register mcp server automatically [IDE-1205]

- src/snyk/common/configuration/configuration.ts
- src/test/unit/common/configuration.test.ts
Regression introduced in #634.
- The regression never made it into a release.
- N/A.
> fix: revert regression in delta configuration [IDE-1256]

- CHANGELOG.md
- src/snyk/common/messages/analysisMessages.ts
- src/snyk/snykCode/views/issueTreeProvider.ts
- src/test/integration/securityIssueTreeProvider.test.ts
> refacto: rename ai fix to agent fix

- .cursorrules
- .github/workflows/release-stable.yaml
- src/snyk/extension.ts
> fix: push tags correctly during release, find mcp endpoint config

- src/snyk/cli/mcp/mcp.ts
- src/snyk/cli/mcp/text.ts
- src/test/unit/cli/mcp/text.test.ts
> fix: send IDE trusted folders to MCP server
